seed: 42

gencode:
  enabled: true
  kwargs:
    fasta: ../../data/raw/genome/GRCh38.primary_assembly.genome.fa
    gtf:   ../../data/raw/gencode/gencode.v44.annotation.gtf
    out:   ../../data/cache/gencode_v44_structural_base
    window: 131072            # 128k windows
    stride: 65536             # 64k step
    bin_size: 1               # base-resolution labels to match NTEncoder
    chroms: "chr1,chr2"       # set "" to process all chr*
    max_shard_bases: 50000000

gtex:
  enabled: true
  kwargs:
    junctions: "../../data/gtex/junctions/*.parquet"  # per-sample junction counts
    gtf:          ../../data/raw/gencode.v44.annotation.gtf
    out:          ../../data/cache/gtex_psi
    chroms:       ""        # or "chr1,chr2"
    min_count:    5         # per-junction minimum count per sample
    min_total:    20        # per-sample total junction count threshold
    min_samples:  5         # require junction observed in ≥ this many samples

variants:
  enabled: true
  kwargs:
    vcf:           ../../data/variants/cohort.vcf.gz
    windows_glob:  ../../data/cache/gencode_v44_structural_base/*.parquet  # align variants to these windows
    out:           ../../data/cache/variants_aligned
    apply_alt:     true      # write ALT-applied sequences alongside channels
    max_per_window: 64       # safety cap per window
    shard_size:     50000    # rows per output shard (tune for I/O)

aggregate:
  enabled: true
  kwargs:
    # Your prepare_data module can merge/index these inputs as needed.
    input_dir:   ../../data/cache/gencode_v44_structural_base
    output_dir:  ../../data/processed/structural
    gtex_dir:    ../../data/cache/gtex_psi
    variant_dir: ../../data/cache/variants_aligned
    # Add any extra switches your aggregator understands, e.g.:
    # write_index: true
    # split_by: "chrom"
    # keep_columns: ["chrom","start","end","seq","donor","acceptor","tss","polya"]

outputs:
  # Prefer asserting existence via globs (works for Parquet shard outputs).
  dir: ../../data/cache/gencode_v44_structural_base
  expect:
    - shard_*.parquet
    # If your aggregator writes additional outputs, add their patterns too, e.g.:
    # - ../../data/cache/gtex_psi/*.parquet
    # - ../../data/cache/variants_aligned/*.parquet