seed: 42
task: structural

data:
  train_parquet_glob: ../../data/cache/gencode_v44_structural_base/shard_*.parquet
  val_parquet_glob:   ../../data/cache/gencode_v44_structural_base/shard_*.parquet
  batch_size: 2
  num_workers: 2

model:
  freeze_encoder: true  # Set to false if you want to fine-tune the encoder
  encoder:
    model_id: InstaDeepAI/nucleotide-transformer-500m-human-ref
    hidden_size: 1280
  heads:
    hidden: 512
    use_conv: true
    dropout: 0.1
  loss:
    pos_weight: 25.0
    w_splice: 1.0
    w_tss: 0.5
    w_polya: 0.5
  decoder: {}  # optional; not used during structural training loss

optim:
  lr: 2.0e-4
  weight_decay: 0.01

trainer:
  epochs: 2
  devices: 1
  ckpt_dir: checkpoints/structural
  logdir: runs/structural
  early_stopping_patience: 2